version: '3.8' # Docker Compose 파일 버전

services:
  # Redis 서비스
  redis:
    image: "redis:latest" # Docker Hub의 최신 Redis 이미지를 사용합니다.
    container_name: withmorning-redis # 컨테이너 이름을 지정합니다.
    ports:
      - "6379:6379" # 호스트와 컨테이너의 Redis 포트를 연결합니다.
     #서버가 재시작되어도 Redis 데이터가 유지되도록 볼륨을 설정할 수 있습니다. (선택 사항)
    volumes:
      - redis-data:/data

