version: '3.8' # Docker Compose 파일 버전

services:
  # Spring Boot 애플리케이션 서비스
  app:
    image: ${DOCKER_IMAGE_NAME}
    container_name: withmorning-app
    ports:
      - "8080:8080" # 호스트의 8080 포트를 컨테이너의 8080 포트와 연결합니다.
    depends_on:
      - redis # redis 서비스가 시작된 후에 app 서비스가 시작됩니다.
    environment:
      # Redis 설정
      - SPRING_REDIS_HOST=redis

      # 데이터베이스(DB) 설정
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

      # JWT 설정
      - JWT_SECRET=${JWT_SECRET}

      # Apple 소셜 로그인 설정
      - REDIRECT_URL=${REDIRECT_URL}
      - CLIENT_ID=${CLIENT_ID}
      - TEAM_ID=${TEAM_ID}
      - KEY_ID=${KEY_ID}

      # AWS S3 설정
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}

      # CoolSMS 설정
      - COOLSMS_KEY=${COOLSMS_KEY}
      - COOLSMS_SECRET=${COOLSMS_SECRET}
      - FROM_NUMBER=${FROM_NUMBER}
    volumes:
      # 이제 변수 없이 고정된 경로를 사용합니다.
      - ./firebase-service-account.json:./firebase-service-account.json
      - ./authkey.p8:./authkey.p8 # 파일 이름을 authkey.p8로 단순화

  # Redis 서비스
  redis:
    image: "redis:latest" # Docker Hub의 최신 Redis 이미지를 사용합니다.
    container_name: withmorning-redis # 컨테이너 이름을 지정합니다.
    ports:
      - "6379:6379" # 호스트와 컨테이너의 Redis 포트를 연결합니다.