version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: withmorning-redis
    ports:
      - "6379:6379"
    volumes:
      # 컨테이너의 /data 디렉터리를 'redis-data' 볼륨과 연결
      - redis-data:/data

# ✅ 이 부분의 주석을 제거하여 'redis-data' 볼륨을 선언합니다.
volumes:
  redis-data: