spring:
  # .env import
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  # JWT 설정 추가
security:
  jwt:
    secret-key: ${JWT_SECRET}
    access-expiration-time: 180000 # 3분
    refresh-expiration-time: 604800000  # 7일
oauth2:
  provider:
    apple:
      auth:
        token-url: https://appleid.apple.com/auth/token
      redirect:
        url: ${REDIRECT_URL}
      client:
        id: ${CLIENT_ID}
      team:
        id: ${TEAM_ID}
      key:
        id: ${KEY_ID}
        path: file:./AuthKey_${KEY_ID}.p8


fcm:
  service-account-file: file:./firebase-service-account.json

