spring:
  # .env import
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  apple:
    team:
      id: ${TEAM_ID}
    login:
      key: ${KEY_ID}
    client:
      id: ${CLIENT_ID}
    redirect:
      url: https://withmorning.site/apple/callback
    key:
      path: ../../../../AuthKey_3N2GZNNVW2.p8

fcm:
  service-account-file: file:./firebase-service-account.json

