name: Java CI

on:
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # 1) 워크플로우 실행 전 기본적으로 체크아웃 필요
      - uses: actions/checkout@v3

      # 2) JDK 11 버전 설치, 다른 JDK 버전을 사용한다면 수정 필요
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3)권한 부여 >> 리눅스 명령어다
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      # 4) .build시작 >> 리눅스 명령어다. 6,7번 내용은 어지간해서 바뀌지 않는다.
      - name: Build with Gradle
        #run: ./gradlew clean build -x test
        # -x test 테스트
        run: ./gradlew clean build
        shell: bash